FROM php:8.4-fpm

# Set working directory
WORKDIR /www/websites/tickerwolf.ai

# Install dependencies
RUN export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" && \
    apt-get update && apt-get install -y \
    build-essential \
    mariadb-client \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libmagickwand-dev \
    libzip-dev \
    locales \
    imagemagick \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl
#    wkhtmltopdf

RUN pecl install redis && docker-php-ext-enable redis

RUN pecl install excimer && docker-php-ext-enable excimer

RUN pecl install xdebug && docker-php-ext-enable xdebug

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Get Imagick Extension
RUN git clone https://github.com/Imagick/imagick \
 && cd imagick \
 && phpize && ./configure \
 && make \
 && make install

# Move the imagick extension
RUN cd imagick \
&& EXTENSION_DIR="$( php -i | grep ^extension_dir | awk -F '=>' '{print $2}' | xargs )" \
&& if [ ! -d "${EXTENSION_DIR}" ]; then mkdir -p "${EXTENSION_DIR}"; fi \
&& cp ./modules/imagick.so "${EXTENSION_DIR}/imagick.so" \
&& cd ../ \
&& rm -rf imagick \
&& echo -n 'extension=imagick.so' > /usr/local/etc/php/conf.d/90-imagick.ini

# Install extensions
RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg
RUN docker-php-ext-install pdo_mysql zip exif pcntl bcmath mysqli sockets gd intl

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Change current user to www
USER www

# Copy existing application directory permissions
COPY --chown=www:www . /www/websites/tickerwolf.ai

#RUN php composer install

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]