/**
 * --------------------------------------------------------------------------
 * TickerWolf.ai — Inertia App Entry
 * --------------------------------------------------------------------------
 * Bootstraps the Inertia + Vue 3 single-page application.
 *
 * Responsibilities:
 *  • Initialize Inertia with Ziggy routing and CSRF protection
 *  • Register Lineone’s default layout globally
 *  • Load Lineone’s compiled CSS and JS assets (via Vite)
 *  • Manage dark/light theme
 * --------------------------------------------------------------------------
 */

import '../css/lineone/app.css' // ✅ Core Lineone styles (includes base, components, pages, etc.)

import { createApp, h } from 'vue'
import { createInertiaApp } from '@inertiajs/vue3'
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers'
import type { DefineComponent } from 'vue'

import { initializeTheme } from './composables/useAppearance'
import { ensureCsrfCookie } from './auth'

// Lineone default layout for all Inertia pages
//import AppLayout from '@/lineone/layouts/AppLayout.vue'

// Ziggy (route helper)
import { ZiggyVue, route } from 'ziggy-js'
import { Ziggy } from './ziggy' // Generated by `php artisan ziggy:generate`

// ---------------------------------------------------------------------------
// Global route() helper on window
// ---------------------------------------------------------------------------
declare global {
  interface Window {
    route: (name?: string, params?: any, absolute?: boolean) => string
  }
}

window.route = ((name?: string, params?: any, absolute?: boolean) => {
  if (!name) {
    // @ts-expect-error Allow Router return for convenience
    return route(undefined, undefined, absolute, Ziggy)
  }
  return route(name as string, params, absolute, Ziggy)
}) as typeof window.route

const appName = import.meta.env.VITE_APP_NAME || 'TickerWolf.ai'

// ---------------------------------------------------------------------------
// Inertia App Boot
// ---------------------------------------------------------------------------
createInertiaApp({
  title: (title) => (title ? `${title} - ${appName}` : appName),

  resolve: async (name) => {
    const pages = import.meta.glob<DefineComponent>('./pages/**/*.vue')
    const page = await resolvePageComponent(`./pages/${name}.vue`, pages)

    // Auto-wrap pages with Lineone layout if none provided
    if (!page.default.layout) {
      page.default.layout = AppLayout
    }

    return page
  },

  setup({ el, App, props, plugin }) {
    const vueApp = createApp({ render: () => h(App, props) })

    vueApp.use(plugin)
    vueApp.use(ZiggyVue, Ziggy)

    ensureCsrfCookie()
    vueApp.mount(el)
  },

  progress: { color: '#4B5563' },
})

// Initialize Lineone dark/light theme behavior
initializeTheme()