import '../css/app.css';

import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import type { DefineComponent } from 'vue';
import { createApp, h } from 'vue';
import { initializeTheme } from './composables/useAppearance';

import { ensureCsrfCookie } from './auth';

// Use named imports from Ziggy
import { ZiggyVue, route } from 'ziggy-js';
import { Ziggy } from './ziggy'; // Generated by `php artisan ziggy:generate`

// Make route() globally available (so you can use it anywhere)
window.route = (name?: string, params?: any, absolute?: boolean) =>
    route(name, params, absolute, Ziggy);

const appName = import.meta.env.VITE_APP_NAME || 'Laravel';

createInertiaApp({
    title: (title) => (title ? `${title} - ${appName}` : appName),
    resolve: (name) =>
        resolvePageComponent(
            `./pages/${name}.vue`,
            import.meta.glob<DefineComponent>('./pages/**/*.vue'),
        ),
    setup({ el, App, props, plugin }) {
        const vueApp = createApp({ render: () => h(App, props) });

        vueApp.use(plugin);

        // Register Ziggy Vue plugin with your routes
        vueApp.use(ZiggyVue, Ziggy);

        // Initialize CSRF protection once when app mounts
        ensureCsrfCookie();

        vueApp.mount(el);
    },
    progress: { color: '#4B5563' },
});

// Initialize dark/light theme handling
initializeTheme();